# Generated by Django 3.0.7 on 2020-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='feels_like',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='max_temp',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='min_temp',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
