# Generated by Django 3.0.7 on 2020-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20200623_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='City',
            name='icon',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
