# Generated by Django 3.0.7 on 2020-06-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_city_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='City',
            name='description',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
